spring:
  application:
    name: ThymeLeaf To PDF

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=postgresThymeLeaf
    username: postgres
    password: 123456789
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      #      ddl-auto: update
      ddl-auto: update
    properties:
      hibernate:
        default_schema: postgresThymeLeaf
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect